export const ADMIN_AUTHENTICATION_REPOSITORY = Symbol(
  'ADMIN_AUTHENTICATION_REPOSITORY',
);
export const ADMIN_LOGIN_CHALLENGE_TOKEN_ISSUER = Symbol(
  'ADMIN_LOGIN_CHALLENGE_TOKEN_ISSUER',
);
export const ADMIN_LOGIN_RATE_LIMITER = Symbol('ADMIN_LOGIN_RATE_LIMITER');
export const ADMIN_PASSWORD_HASHER = Symbol('ADMIN_PASSWORD_HASHER');
export const ADMIN_PASSWORD_LOGIN_SERVICE = Symbol('ADMIN_PASSWORD_LOGIN_SERVICE');
export const ADMIN_MFA_REPOSITORY = Symbol('ADMIN_MFA_REPOSITORY');
export const ADMIN_MFA_SECRET_CIPHER = Symbol('ADMIN_MFA_SECRET_CIPHER');
export const ADMIN_TOTP_AUTHENTICATOR = Symbol('ADMIN_TOTP_AUTHENTICATOR');
export const ADMIN_RECOVERY_CODE_ISSUER = Symbol('ADMIN_RECOVERY_CODE_ISSUER');
export const ADMIN_AUTHENTICATION_GRANT_TOKEN_ISSUER = Symbol(
  'ADMIN_AUTHENTICATION_GRANT_TOKEN_ISSUER',
);
export const ADMIN_MFA_SERVICE = Symbol('ADMIN_MFA_SERVICE');
