export const ADMIN_AUTHENTICATION_REPOSITORY = Symbol('ADMIN_AUTHENTICATION_REPOSITORY');
export const ADMIN_LOGIN_CHALLENGE_TOKEN_ISSUER = Symbol('ADMIN_LOGIN_CHALLENGE_TOKEN_ISSUER');
export const ADMIN_LOGIN_RATE_LIMITER = Symbol('ADMIN_LOGIN_RATE_LIMITER');
export const ADMIN_PASSWORD_HASHER = Symbol('ADMIN_PASSWORD_HASHER');
export const ADMIN_PASSWORD_LOGIN_SERVICE = Symbol('ADMIN_PASSWORD_LOGIN_SERVICE');
