export const ADMIN_SESSION_REPOSITORY = Symbol('ADMIN_SESSION_REPOSITORY');
export const ADMIN_SESSION_TOKEN_ISSUER = Symbol('ADMIN_SESSION_TOKEN_ISSUER');
export const ADMIN_SESSION_SERVICE = Symbol('ADMIN_SESSION_SERVICE');
export const ADMIN_SESSION_COOKIE_CONFIGURATION = Symbol('ADMIN_SESSION_COOKIE_CONFIGURATION');
