export const API_CLIENT_REPOSITORY = Symbol('API_CLIENT_REPOSITORY');
export const API_CLIENT_KEY_ISSUER = Symbol('API_CLIENT_KEY_ISSUER');
export const API_CLIENT_RATE_LIMITER = Symbol('API_CLIENT_RATE_LIMITER');
export const API_CLIENT_ADMINISTRATION_SERVICE = Symbol(
  'API_CLIENT_ADMINISTRATION_SERVICE',
);
export const API_CLIENT_AUTHENTICATION_SERVICE = Symbol(
  'API_CLIENT_AUTHENTICATION_SERVICE',
);
