packages:
  - apps/*
  - packages/*

autoInstallPeers: true
linkWorkspacePackages: true
preferWorkspacePackages: true
sharedWorkspaceLockfile: true
strictPeerDependencies: false

allowBuilds:
  '@scarf/scarf': false
  esbuild: true
  msgpackr-extract: true

minimumReleaseAgeExclude:
  - '@nestjs/swagger@12.0.1'
  - bullmq@6.3.2
  - zod@4.5.1
