export const WORKER_EVENTING_REPOSITORY = Symbol('WORKER_EVENTING_REPOSITORY');
export const WORKER_EVENTING_QUEUE = Symbol('WORKER_EVENTING_QUEUE');
export const WORKER_OUTBOX_SERVICE = Symbol('WORKER_OUTBOX_SERVICE');
export const WORKER_OUTBOX_CONSUMER_SERVICE = Symbol('WORKER_OUTBOX_CONSUMER_SERVICE');
export const WORKER_WEBHOOK_SECRET_CIPHER = Symbol('WORKER_WEBHOOK_SECRET_CIPHER');
export const WORKER_WEBHOOK_SENDER = Symbol('WORKER_WEBHOOK_SENDER');
export const WORKER_WEBHOOK_DELIVERY_SERVICE = Symbol('WORKER_WEBHOOK_DELIVERY_SERVICE');
export const WORKER_PUBLICATION_COMMAND = Symbol('WORKER_PUBLICATION_COMMAND');
export const WORKER_PUBLICATION_SCHEDULE_PROCESSOR = Symbol(
  'WORKER_PUBLICATION_SCHEDULE_PROCESSOR',
);
export const WORKER_OUTBOX_RELAY_SERVICE = Symbol('WORKER_OUTBOX_RELAY_SERVICE');
