export const EVENTING_REPOSITORY = Symbol('EVENTING_REPOSITORY');
export const OUTBOX_SERVICE = Symbol('OUTBOX_SERVICE');
export const OUTBOX_ADMINISTRATION_SERVICE = Symbol('OUTBOX_ADMINISTRATION_SERVICE');
export const WEBHOOK_ADMINISTRATION_SERVICE = Symbol('WEBHOOK_ADMINISTRATION_SERVICE');
export const PUBLICATION_SCHEDULING_SERVICE = Symbol('PUBLICATION_SCHEDULING_SERVICE');
export const WEBHOOK_SECRET_CIPHER = Symbol('WEBHOOK_SECRET_CIPHER');
export const WEBHOOK_SECRET_GENERATOR = Symbol('WEBHOOK_SECRET_GENERATOR');
