export const CONTENT_ASSET_REPOSITORY = Symbol('CONTENT_ASSET_REPOSITORY');
export const CONTENT_REPOSITORY = Symbol('CONTENT_REPOSITORY');
export const CONTENT_SERVICE = Symbol('CONTENT_SERVICE');
export const CONTENT_PUBLICATION_REPOSITORY = Symbol('CONTENT_PUBLICATION_REPOSITORY');
export const CONTENT_PUBLICATION_SERVICE = Symbol('CONTENT_PUBLICATION_SERVICE');
export const CONTENT_DELIVERY_SERVICE = Symbol('CONTENT_DELIVERY_SERVICE');
