export const ErrorCode = {
  ACTION_NOT_ALLOWED: 'ACTION_NOT_ALLOWED',
  ADMIN_EMAIL_ALREADY_EXISTS: 'ADMIN_EMAIL_ALREADY_EXISTS',
  ADMIN_OWNER_ALREADY_EXISTS: 'ADMIN_OWNER_ALREADY_EXISTS',
  ADMIN_PASSWORD_POLICY_FAILED: 'ADMIN_PASSWORD_POLICY_FAILED',
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  FORBIDDEN: 'FORBIDDEN',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
  MFA_REQUIRED: 'MFA_REQUIRED',
  NOT_FOUND: 'NOT_FOUND',
  RATE_LIMITED: 'RATE_LIMITED',
  REAUTH_REQUIRED: 'REAUTH_REQUIRED',
  REQUEST_CONTEXT_REQUIRED: 'REQUEST_CONTEXT_REQUIRED',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  VERSION_CONFLICT: 'VERSION_CONFLICT',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
