export const PROJECT_DEPLOYMENT_REPOSITORY = Symbol('PROJECT_DEPLOYMENT_REPOSITORY');
export const PROJECT_DEPLOYMENT_ADMINISTRATION_SERVICE = Symbol(
  'PROJECT_DEPLOYMENT_ADMINISTRATION_SERVICE',
);
export const DEPLOYMENT_CALLBACK_SERVICE = Symbol('DEPLOYMENT_CALLBACK_SERVICE');
