import 'dotenv/config';
import 'reflect-metadata';

import path from 'node:path';

import { DataSource } from 'typeorm';

import {
  AdminAccountEntity,
  AdminAuthenticationGrantEntity,
  AdminLoginAttemptEntity,
  AdminLoginChallengeEntity,
  AdminMfaMethodEntity,
  AdminRecoveryCodeEntity,
  AdminSessionEntity,
  ApiClientAllowedOriginEntity,
  ApiClientEntity,
  ApiClientKeyEntity,
  ApiClientScopeEntity,
  ApiClientSiteAccessEntity,
  AssetEntity,
  AssetProcessingAttemptEntity,
  AssetUploadSessionEntity,
  AssetVariantEntity,
  AssetUsageEntity,
  AuditLogEntity,
  ContentDraftEntity,
  ContentEntity,
  ContentPublicationEntity,
  ContentRevisionEntity,
  ContentSiteEntity,
  DeploymentEntity,
  DeploymentEventEntity,
  EnvironmentEntity,
  HealthCheckEntity,
  IdempotencyRecordEntity,
  MemberAdminNoteEntity,
  MemberEntity,
  ProjectEntity,
  ProjectEventEntity,
  ProjectSiteEntity,
  ReleaseEntity,
  RepositoryConnectionEntity,
  ResourceAssetEntity,
  ResourceCollectionEntity,
  ResourceEntity,
  ResourceRelationEntity,
  ResourceTagAssignmentEntity,
  ResourceTagEntity,
  ServiceEntity,
  ServiceEnvironmentEntity,
  SiteDomainEntity,
  SiteEntity,
  SiteMembershipEntity,
  SiteSettingsEntity,
  WorkspaceEntity,
} from '@atlas/server';

const packageRoot = path.resolve(__dirname, '..');
const compiledRuntime = path.basename(__dirname) === 'dist';

const databaseUrl = process.env.DATABASE_URL;

if (!databaseUrl) {
  throw new Error('DATABASE_URL is required to use the TypeORM DataSource.');
}

export const atlasDataSource = new DataSource({
  type: 'postgres',
  url: databaseUrl,
  synchronize: false,
  migrationsRun: false,
  logging: process.env.NODE_ENV === 'development',
  migrationsTableName: 'atlas_migrations',
  entities: [
    AuditLogEntity,
    AdminAccountEntity,
    AdminLoginAttemptEntity,
    AdminLoginChallengeEntity,
    AdminMfaMethodEntity,
    AdminRecoveryCodeEntity,
    AdminAuthenticationGrantEntity,
    AdminSessionEntity,
    WorkspaceEntity,
    SiteEntity,
    SiteDomainEntity,
    SiteSettingsEntity,
    ApiClientEntity,
    ApiClientSiteAccessEntity,
    ApiClientScopeEntity,
    ApiClientAllowedOriginEntity,
    ApiClientKeyEntity,
    ProjectEntity,
    ProjectSiteEntity,
    ProjectEventEntity,
    RepositoryConnectionEntity,
    ReleaseEntity,
    EnvironmentEntity,
    ServiceEntity,
    ServiceEnvironmentEntity,
    DeploymentEntity,
    DeploymentEventEntity,
    HealthCheckEntity,
    IdempotencyRecordEntity,
    ResourceCollectionEntity,
    ResourceTagEntity,
    ResourceEntity,
    ResourceTagAssignmentEntity,
    ResourceRelationEntity,
    ResourceAssetEntity,
    MemberEntity,
    SiteMembershipEntity,
    MemberAdminNoteEntity,
    ContentEntity,
    ContentDraftEntity,
    ContentRevisionEntity,
    AssetUsageEntity,
    ContentSiteEntity,
    ContentPublicationEntity,
    AssetEntity,
    AssetUploadSessionEntity,
    AssetVariantEntity,
    AssetProcessingAttemptEntity,
  ],
  migrations: [
    path.join(packageRoot, compiledRuntime ? 'dist/migrations/*.js' : 'src/migrations/*.ts'),
  ],
});

export default atlasDataSource;
